config/routes.rb
Rails.application.routes.draw do
  resources :images
  root 'images#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to image_url(@image), notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:image_name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image_name %>
    <%= form.text_field :image_name, required: true %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, required: true %>
  </div>

  <div class="actions">
    <%= form.submit "#{from} Image", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image, from: "Update" %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="main-title"><b>Images</b></h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>S.No</th>
      <th>Image name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @images.present? %>
      <% @images.each_with_index do |image, ind| %>
        <tr>
          <td class="action-btn"><%= ind + 1 %></td>
          <td><%= image.image_name %></td>
          <td class="action-btn"><%= link_to 'Show', image, class: "btn btn-info"%></td>
          <td class="action-btn"><%= link_to 'Edit', edit_image_path(image), class: "btn btn-primary" %></td>
          <td class="action-btn"><%= link_to 'Destroy', image, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% else %>
      <tr><td colspan="4" class="no-data-found">Images not found !</td></tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Upload New Image', new_image_path, class: "btn btn-primary new-btn" %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image, from: "Save" %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>


<div class="img-title">
  <h1><strong><%= @image.image_name %></strong></h1>
</div>

<p class="img-body">
  <% if @image.image? %>
    <%= image_tag @image.image.url %>
  <% end %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageCrudApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>